// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _10_dotnet.Data;

#nullable disable

namespace _10_dotnet.Migrations
{
    [DbContext(typeof(DotNetDbContext))]
    [Migration("20251127084902_Adding Images Table")]
    partial class AddingImagesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_10_dotnet.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            id = new Guid("d5044492-5690-4883-8e05-4fb0233e30de"),
                            Name = "Easy"
                        },
                        new
                        {
                            id = new Guid("64136753-eb5a-438a-ad3a-55ff87b1e9ba"),
                            Name = "Medium"
                        },
                        new
                        {
                            id = new Guid("617d2eeb-3107-4cde-a56d-be0eb69c1ef1"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("_10_dotnet.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSizeInBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("_10_dotnet.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            id = new Guid("6c09db5c-ec99-43e6-94db-3a8833fe4430"),
                            Code = "AKL",
                            Name = "Auckland",
                            RegionImageUrl = "https://wallpaperaccess.com/full/9352734.jpg"
                        },
                        new
                        {
                            id = new Guid("813f1efa-cbaf-4251-9809-20b695508ecd"),
                            Code = "WLG",
                            Name = "Wellington",
                            RegionImageUrl = "https://www.siliconera.com/wp-content/uploads/2022/06/bakemonogatarimanga.png"
                        },
                        new
                        {
                            id = new Guid("e6bf5231-0dce-42fe-be3d-2886e582e863"),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://pixelz.cc/wp-content/uploads/2019/12/lightning-returns-final-fantasy-xiii-uhd-4k-wallpaper.jpg"
                        },
                        new
                        {
                            id = new Guid("e924e018-7902-46c6-9a97-079b1305a580"),
                            Code = "STL",
                            Name = "Southland"
                        });
                });

            modelBuilder.Entity("_10_dotnet.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("_10_dotnet.Models.Domain.Walk", b =>
                {
                    b.HasOne("_10_dotnet.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_10_dotnet.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
